Handling for the .gnupg folder implemented

diff --git a/dotfiles b/dotfiles
--- a/dotfiles
+++ b/dotfiles
@@ -6,6 +6,9 @@ REPO_PATH="${HOME}/.dotfiles"
 # Defining the path for the vim files
 VIM_PATH="${HOME}/.vim"
 
+# Defining the path for the gnupg files
+GPG_PATH="${HOME}/.gnupg"
+
 # Defining the path for the file in which the files are mapped for the path
 MAP_FILE="dotfiles.map"
 
@@ -157,6 +160,11 @@ function _help () {
   2. 'dotfiles vimsetup-remote' to specify the remote repository to sync.
   THIS MUST NOT BE THE SAME REPOSITORY AS YOUR DOTFILES REPOSITORY.
   3. 'dotfiles vimsync' to sync your vimfiles to the remote repository.
+
+  Usage for the .gnupg folder
+  ---------------------------
+  Just like the usage for the vimfiles, but replace 'vim' with 'gpg' in your commands.
+  USE A PRIVATE REPOSITORY!
   
   
   Author
@@ -325,6 +333,8 @@ function _status () {
   git status
 }
 
+### VIM ###
+
 # Getting the status of the vim repository
 function _vimstatus () {
 	cd $VIM_PATH
@@ -393,6 +403,77 @@ function _vimsync () {
 	else
 		die "~/.vim does not exist."
 	fi
+}
+
+### GNUPG ###
+# Getting the status of the gnupg repository
+function _gpgstatus () {
+  cd $GPG_PATH
+  if [[ ! -d .git ]]; then
+    die "No gnupg repository initialized."
+  else
+    git status
+  fi
+}
+
+# Initializes the gnupg path
+function _gpgsetup () {
+    # If the GPG_PATH is defined, then create it or die
+  if [[ ! -d $GPG_PATH ]] ; then
+    mkdir $GPG_PATH || die "Could not create gnupg repository"
+  fi
+
+  # If the GPG_PATH still does not exist, die anyway
+  [[ -d $GPG_PATH ]] || die "No repo !?"
+
+  # Change into the repo path, and init a git if it is not initialized yet
+  cd $GPG_PATH && [[ ! -d .git ]] && git init .
+  
+}
+
+function _gpgsetup-remote () {
+  # cd to GPG_PATH if vim_path exists
+  if [[ -d $GPG_PATH ]]; then
+    cd $GPG_PATH
+    # If a git repo is initialized, do this
+    if [[ -d .git ]]; then
+      # Read the remote url from the command line 
+      local remote="$1"
+
+      # If the remote is not specified, die
+      [[ -z "$remote" ]] && die "No remote specified"
+
+      # Add the remote as origin from the variable
+      git remote add origin "$remote"
+      echo "Remote Repository $remote added."
+    else
+      die "No git repository for the gnupg files initialized. Run 'dotfiles gpgsetup' first."
+    fi
+  else
+    die "~/.gnupg does not exist."
+  fi
+}
+
+function _gpgsync () {
+  # cd to gnupg path if gnupg path exists
+  if [[ -d $GPG_PATH ]]; then
+    cd $GPG_PATH
+    # If a git repo is initialized, do this
+    if [[ -d .git ]]; then
+      # Add all files
+      git add -A
+      # Commit them with a short commitmsg
+      git commit -m "Update from $HOSTNAME ($(date))"
+      # Pull from the repository and merge
+      git pull origin master
+      # Then push back to the repository again
+      git push origin master
+    else
+      die "No git repository for the gnupg files initialized. Run 'dotfiles gpgsetup' first."
+    fi
+  else
+    die "~/.gnupg does not exist."
+  fi
 }
 
 main $@
